# Generated by Django 3.0.5 on 2020-04-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csuser',
            options={'verbose_name': '커뮤니티 회원', 'verbose_name_plural': '커뮤니티 회원'},
        ),
        migrations.AddField(
            model_name='csuser',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
