# Generated by Django 3.0.5 on 2020-04-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csuser', '0002_auto_20200414_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csuser',
            old_name='email',
            new_name='useremail',
        ),
    ]
