# Generated by Django 3.0.5 on 2020-04-14 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csuser', '0003_auto_20200414_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csuser.Csuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '커뮤니티 게시글',
                'verbose_name_plural': '커뮤니티 게시글',
                'db_table': 'cscommunity_board',
            },
        ),
    ]
